name: transcriber-qt
channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - cudnn

  - pip:
    - torch
    - transformers
    - datasets
    - tokenizers
    - accelerate
    - librosa
    - soundfile
    - faster-whisper
    - PySide6
    - tqdm
