name: transcriber-qt-speakers-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ffmpeg
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - whisperx
    - PySide6
    - python-dotenv