name: transcriber-qt
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - ffmpeg
  - cudnn=8.*
  - pip
  - pip:
    - torch --index-url https://download.pytorch.org/whl/cu118
    - torchvision --index-url https://download.pytorch.org/whl/cu118
    - torchaudio --index-url https://download.pytorch.org/whl/cu118
    - whisperx
    - PySide6
    - python-dotenv