name: transcriber-qt-speakers
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ffmpeg
  - cudnn=8.*
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch
    - torchvision
    - torchaudio
    - whisperx
    - PySide6
    - python-dotenv